#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

HOME="${APP_DIR}"      && export HOME
NEXT_TELEMETRY_DEBUG=1 && export NEXT_TELEMETRY_DEBUG

redirect_cmd() {
    if [[ "${DEBUG}" == "yes" ]]; then
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}

cd "${APP_DIR}" || exit 1
# shellcheck disable=SC2086
redirect_cmd exec s6-setuidgid hotio yarn start ${ARGS}
